name: Build Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -f Dockerfile -t p-sms-build .
      - name: Build app
        run: docker run --rm -v "$PWD":/home/source p-sms-build
      - name: Print Hash
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: sha256sum presentation/noAnalytics/release/QKSMS-v3.9.4-noAnalytics-release.apk
      - name: Save artifact
        uses: actions/upload-artifact@master
        with:
          name: P-SMS.apk
          path: TMessagesProj/build/outputs/apk/afat/alpha/QKSMS-v3.9.4-noAnalytics-release.apk
